# SPDX-FileCopyrightText: 2024 Kuropen
#
# SPDX-License-Identifier: LicenseRef-KUROPEN-ORG-PUBLIC-CODE

services:
    db:
        image: postgres:16
        environment:
            POSTGRES_PASSWORD: d4cc326a-fe5d-4d09-b694-2b160bc81919
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            -  ./docker-resource/local-data/db:/var/lib/postgresql/data
    redis:
        image: redis:7.2
        restart: unless-stopped
        ports:
            - "6379:6379"
    batch:
        build:
            context: .
            dockerfile: batch.Dockerfile
        depends_on:
            - db
            - redis
        command: "busybox crond -l 2 -L /dev/stderr -f"
        restart: unless-stopped
        volumes:
            - ./.env:/var/www/html/.env:ro
            - ./docker-resource/crontab:/var/spool/cron/crontabs/root:ro
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: postgres
            DB_USERNAME: postgres
            DB_PASSWORD: d4cc326a-fe5d-4d09-b694-2b160bc81919
            CACHE_DRIVER: redis
            SESSION_DRIVER: redis
            REDIS_CLIENT: predis
            REDIS_HOST: redis
            REDIS_PORT: 6379
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
        volumes:
            - ./.env:/var/www/html/.env:ro
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: postgres
            DB_USERNAME: postgres
            DB_PASSWORD: d4cc326a-fe5d-4d09-b694-2b160bc81919
            CACHE_DRIVER: redis
            SESSION_DRIVER: redis
            REDIS_CLIENT: predis
            REDIS_HOST: redis
            REDIS_PORT: 6379
