# SPDX-FileCopyrightText: 2024 Kuropen
#
# SPDX-License-Identifier: CC0-1.0

name: "PHP version check"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-php-ver.yml
      - .github/workflows/migrate-db.yml
      - Dockerfile
      - batch.Dockerfile
  pull_request:
    paths:
      - .github/workflows/test-php-ver.yml
      - .github/workflows/migrate-db.yml
      - Dockerfile
      - batch.Dockerfile
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: "Run Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Version integrity check
        run: bash php-ver-check.sh
